# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"init_available_projects": "01_Create Project.ipynb",
         "summarize_h5": "01_Create Project.ipynb",
         "pgrid_to_run_parameters": "01_Create Project.ipynb",
         "collect_statistics": "01_Create Project.ipynb",
         "fix_geojson": "01_Create Project.ipynb",
         "main": "01_Create Project.ipynb",
         "line2sentences": "01_Tokenizer.ipynb",
         "spattern": "01_Tokenizer.ipynb",
         "isascii": "01_Tokenizer.ipynb",
         "strip_punc_unicode": "01_Tokenizer.ipynb",
         "remove_multiple_spaces": "01_Tokenizer.ipynb",
         "space_pat": "01_Tokenizer.ipynb",
         "isnum": "01_Tokenizer.ipynb",
         "process_line": "01_Tokenizer.ipynb",
         "file2tokens": "01_Tokenizer.ipynb",
         "PATCH_DICT": "01_Tokenizer.ipynb",
         "GensimTokenizer": "01_Tokenizer.ipynb"}

modules = ["create_project.py",
           "tokenizer.py"]

doc_url = "https://bhoov.github.io/junevis/"

git_url = "https://github.com/bhoov/junevis/tree/master/"

def custom_doc_links(name): return None
